import { Collision } from "./Collision";
import { Instance } from "./GameTypes";

// represents a collision on client side
export interface CollisionLocal extends Collision {
  // array of particles randomly generated by the collision
  particles: Array<Instance>;
}